language: python
dist: xenial
python:
- '3.7'
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=ocadotechnologygitlab
  - VCS_SOURCE="https://github.com/${TRAVIS_REPO_SLUG}"
  - secure: "ftXHLw88nByCn2JsxMPcMq3dV8mPO+9Z1i53u/d0KcKxq4zZWb/LyBdocK/ZodAz4fNqAxXsPvC4Q5opU+UgDftlIYcZYvJmorq1kVdwk5thZb4kOj+eAheJy93M3HQbZKOVFO4vrSg6SGafVYthfznm82Qu1HGWdZr/BZHub/JsFBtToHrkS+PlT97Q+gi4H+D15PFz4lbcKiWDSqR5Zj+fGq/5mAiu1QyovCR3j6eL+lX6hOzmaLzdHvqngScNP1dEMaS9fH2WjwxpxlUFFrRm60j+HowuOSSmwKDX645tHpgTJ488RGNntGYPfE2b1cSmmpXmnUq2W1cuvToXwDVaXeF7mKPGvKoXm4SNLhvk2uvpN76qnoNf5TmhEoGf5dIiH1HVlEPQYXHKV/D3QZcEbdhQTeY338R3QhaPpb6RxYYgoqPozSWWfwT4Bt+H8vT3tZjtRD4MGE7VeEWgwH0P+9nuU0B1yn7Cu4zpAd3soMnG1CRv58gPVWiQvw0+C6kQDWCRDI/+JqIc2jcUh+q7taIms3wBbl2AC04tKPaAHocfwuGFWUgsZCM7jZERl8iOyW6UZX4Laz0d/OUDaq33hIBlhPIEbcQoTyInKuN7k0ofcqyHX8tkyBiJElrCFTiaDuwVseDxb6enPVbEhbd7uuCZa7hT3afB3v3SGRc="
  - secure: "NtWEHLvZ6WjQRKFu4y8dSQcduB9V0DKJ99wbTsR5VwqDI4fL+EiG6G/9BZA/xGXe+SB73wHTIUiBHqtedhLmqeCoDaRX3LosHHPKgikqevHZzfsy97Hlvd+UfmKnKT6NiDd4CDuM3JOYCDkKWuAzbB243ge4ddYNP5jBi5eG26P0FlMzriEVgx3CmRhDs8E+Uv4kaFZ0fJm8BYe1hlB7SEWhyWp7nYvIG7ZZ8x2LyE10ZruVB5KbOBzNEewcSrkpyMLXI6Out47cyi9/8r7hQ9jnvwiz64Fj4fIrgRWI4vuyZBrWq/aAgowqJzyCZlwldD8jErD3N+jLtdGVD2OsVgSeHmuo+8aQujWVOOu0C0IdSCKgjzSIBXNXIgj+aKodQG43K/3XEn4y5OBUi6kLCA3QnuKy+SLrZaBhvW+JLefIW6xjSP+GgakgvVqQBAVlgYK/ETS34gUAACk5j4KwDb01FHLUkHwIczAPBe7uurhXr7QhC8Yc+Z+M/S9ed3MTI6a8aKX5AgpK/Vj0Ii96owfLA0/NsyZS3vUW3gOXFIApoJSMYGeR57pq2IdaJve4WRZiSiFrC8fMIz/4BrzLnIO20+5Gu4yztpjeJmtHOjz7D5Y4Dn7/5JqbIkP2MJUGcXvpYVgTMwwFk6FfK2EXSjcF7kqyJyI2zKvTakxNwoo="
  - secure: "GXlT3DOd2GOTClRsBflaQ5fi7xg3aqWgCmBwsyq8r7G6HX3gq4h+vTMRUcpAAtkDLB/sNdi3kD9WlJSmuDJKJhJ2uRS3prt4kB6/kBSAYa6cYWKPhO2RTbRbyxBIgcS/BMtIq80PR7yC/9G6tFRO/Vn6KkcJQ/SUEtIdNbl0Z0G8Ww7uYz/iFTkVrwcjuQQGsRTUO5MGLZlm5+LnP7PlY34BwgIvsOBawFOmmg4ZlIWSu2f5tjf4t7O7wbcAeIrtVzIrskCdD/mrq3O4zKDWQrYL9DRk90+3CWQUWB8PJqFjJ4NCFYpa6jTzlwDVCLMlLjsXuAqR2mSmyZ3qtLhHrIAKzV8WQf+OASwiXr7U2YxD05oRV59XovJgsXWiihfRgLaeq0DaP/TISoid8Xy8riPVlyb+VwhT/emYQCIjN4GwY2TZ+gca/ULTKpWwYv2hg6dLAJigjGrig28zDPMO3hM2NDI0nAnwkSX2J6hDCEGx4nhaJ61mn3suxmnFNw0oDKZ8X8SB5dXywbUy6I0LKzYMqSv6J4EssMr0ggcRrsHYP8yB3zTwDIpAYNR4dLUR7kEHZA1Xo/ZZRYQPz1IBnGAIMOVzziUgW31Gp1YKlXikRPioVPXUkgquc9VEFQOZp7XkXaaYljlPVRbygoyDe1aIhDin9Dv8uZoE4akCBYo="
script:
- npm install -g snyk
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- python ./test.py
- ./.travis/docker-build.sh
after_script:
- docker images
deploy:
  provider: script
  script: ./.travis/docker-push.sh
  on:
    tags: true
    branch: master
